apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "AlertmanagerConfig"
metadata:
  name: "test-web-server"
  labels:
    release: "prom-operator"
spec:
  route:
    groupBy: ["alertname", "severity"]
    receiver: "test-web-server"
    groupWait: "30s"
    groupInterval: "5m"
    repeatInterval: "1h"
    matchers:
      - name: "severity"
        value: "info|testing|warning|error|critical"
        matchType: "=~"
  receivers:
    - name: "test-web-server"
      webhookConfigs:
        - url: "http://test-web-server.testing.svc:9092/"
          sendResolved: true
